// scripts/seo/reporter.js  —  Arlo SEO sub-skill #6 (READ-ONLY writes to reports/ only)
//
// Combines the other sub-skills' results into:
//   (a) a single dated markdown report at reports/seo/YYYY-MM-DD.md, with a
//       plain-English summary at the top (traffic ±, new soft-404s, top-5 quick
//       wins, posts to write), and
//   (b) a paste-ready TAB-SEPARATED row for the "Weekly Analytics Log" sheet:
//       date, sessions, unique visitors, forms, top quick-win keyword, # issues.
// It also DIFFS against the previous report so the summary shows what changed
// week-over-week.
//
// The ONLY thing this suite ever writes is a report file under reports/seo/.
// It never touches the live site (hard constraint).
//
// Standalone: `node scripts/seo/reporter.js [results.json]`
//   - with a results JSON path → renders that.
//   - without → runs the five data sub-skills itself, then writes the report.

import { readFileSync, writeFileSync, mkdirSync, readdirSync, existsSync } from 'fs';
import { today, repoPath, fmtPct, pct, ok, fail, runStandalone } from './lib.js';

const REPORTS_DIR = repoPath('reports', 'seo');

// ─── Machine-state embed (for reliable week-over-week diffing) ─────────────────

const STATE_OPEN = '<!-- SEO-AUDIT-STATE';
const STATE_CLOSE = '-->';

function extractState(md) {
  const i = md.indexOf(STATE_OPEN);
  if (i === -1) return null;
  const j = md.indexOf(STATE_CLOSE, i);
  if (j === -1) return null;
  try { return JSON.parse(md.slice(i + STATE_OPEN.length, j).trim()); } catch { return null; }
}

function previousReport(exclude) {
  if (!existsSync(REPORTS_DIR)) return null;
  const files = readdirSync(REPORTS_DIR)
    .filter(f => /^\d{4}-\d{2}-\d{2}\.md$/.test(f) && f !== exclude)
    .sort();
  if (!files.length) return null;
  const last = files[files.length - 1];
  const md = readFileSync(repoPath('reports', 'seo', last), 'utf8');
  return { file: last, date: last.replace('.md', ''), state: extractState(md) };
}

// ─── Result accessors (tolerate skipped/errored sub-skills) ───────────────────

function byName(results, name) { return results.find(r => r && r.skill === name) || { skill: name, status: 'missing' }; }
function softCount(tech) {
  if (tech.status !== 'ok') return 0;
  // Count real soft-404 findings only — not the 'soft-404-skipped' marker
  // emitted when the live probe couldn't run.
  return (tech.issues || []).filter(i => i.type === 'soft-404' || i.type === 'soft-404-redirect').length;
}
function softProbeSkipped(tech) {
  return tech.status === 'ok' && (tech.issues || []).some(i => i.type === 'soft-404-skipped');
}

// ─── Markdown rendering ───────────────────────────────────────────────────────

export function renderReport(results, prev) {
  const date = today();
  const tech = byName(results, 'technical-audit');
  const gsc = byName(results, 'gsc-quickwins');
  const traffic = byName(results, 'traffic-report');
  const nap = byName(results, 'local-nap');
  const gap = byName(results, 'content-gap');

  const curSoft = softCount(tech);
  const prevSoft = prev?.state?.softIssues ?? null;
  const softDelta = prevSoft == null ? null : curSoft - prevSoft;
  const totalTechIssues = tech.status === 'ok' ? tech.totalIssues : null;

  const curSessions = traffic.status === 'ok' ? traffic.sessions : null;
  const sessionChange = traffic.status === 'ok' ? (traffic.changeVsPrev?.sessions ?? 'n/a')
    : (prev?.state?.sessions != null && curSessions != null ? fmtPct(pct(curSessions, prev.state.sessions)) : 'n/a');

  const topWins = gsc.status === 'ok' ? gsc.quickWins.slice(0, 5) : [];
  const topGaps = gap.status === 'ok' ? gap.topGaps.slice(0, 5) : [];

  const L = [];
  L.push(`# SEO Audit — ${date}`);
  L.push('');
  L.push(`_Generated by ${'`Arlo`'} · read-only · run \`npm run seo:audit\`_`);
  L.push('');

  // ── Plain-English summary ──
  L.push('## Summary');
  L.push('');
  const trafficLine = curSessions != null
    ? `**Traffic:** ${curSessions} sessions (${sessionChange} vs. previous period).`
    : `**Traffic:** Vercel Analytics not available this run (${traffic.status === 'skipped' ? 'no token' : traffic.status}).`;
  L.push(`- ${trafficLine}`);
  const softLine = tech.status === 'ok'
    ? `**Soft-404s:** ${curSoft} found${softDelta == null ? '' : ` (${softDelta >= 0 ? '+' : ''}${softDelta} vs. last report)`}${softProbeSkipped(tech) ? ' — _live probe skipped this run (site unreachable); analyzed the checked-out build. Re-run where the live site is reachable for the real soft-404 check._' : ''}.`
    : `**Soft-404s:** technical audit ${tech.status}.`;
  L.push(`- ${softLine}`);
  if (totalTechIssues != null) L.push(`- **Technical issues:** ${totalTechIssues} total (${tech.bySeverity.map(s => `${s.count} ${s.label.toLowerCase()}`).join(', ')}).`);
  if (topWins.length) L.push(`- **Top quick win:** "${topWins[0].query}" — position ${topWins[0].position}, ${topWins[0].impressions} impressions, ${topWins[0].ctr}% CTR.`);
  else L.push(`- **Quick wins:** GSC ${gsc.status === 'ok' ? 'returned none in range' : gsc.status}.`);
  if (topGaps.length) L.push(`- **Write these next:** ${topGaps.map(g => `“${g.suggestedTitle}”`).slice(0, 3).join('; ')}.`);
  if (nap.status === 'ok' && !nap.summary.internalConsistent) L.push(`- **NAP:** internal phone/address inconsistency detected — see below.`);
  L.push('');

  // ── Week-over-week ──
  L.push('## What changed since last report');
  if (!prev) L.push('- _No previous report to diff against — this is the first run._');
  else {
    L.push(`- Comparing against \`${prev.file}\`.`);
    if (prev.state?.sessions != null && curSessions != null) L.push(`- Sessions: ${prev.state.sessions} → ${curSessions} (${fmtPct(pct(curSessions, prev.state.sessions))}).`);
    if (softDelta != null) L.push(`- Soft-404s: ${prevSoft} → ${curSoft} (${softDelta >= 0 ? '+' : ''}${softDelta}).`);
    if (prev.state?.totalTechIssues != null && totalTechIssues != null) L.push(`- Technical issues: ${prev.state.totalTechIssues} → ${totalTechIssues}.`);
    if (prev.state?.quickWins != null && gsc.status === 'ok') L.push(`- Quick wins: ${prev.state.quickWins} → ${gsc.quickWinsCount}.`);
  }
  L.push('');

  // ── 1. Technical audit ──
  L.push('## 1. Technical audit');
  if (tech.status !== 'ok') L.push(`- _${tech.status}: ${tech.note || ''}_`);
  else {
    L.push(`- Mode: **${tech.mode}** · pages analyzed: ${tech.pagesAnalyzed} · sitemap URLs: ${tech.sitemapUrls} · issues: **${tech.totalIssues}**`);
    L.push('');
    if (tech.issues.length) {
      L.push('| Severity | Type | URL | Detail |');
      L.push('|---|---|---|---|');
      for (const i of tech.issues.slice(0, 60)) L.push(`| ${i.severity} | ${i.type} | \`${trunc(i.url, 60)}\` | ${md(i.note)} |`);
    } else L.push('- No issues found. ✅');
  }
  L.push('');

  // ── 2. GSC quick wins ──
  L.push('## 2. Search Console quick wins');
  if (gsc.status !== 'ok') L.push(`- _${gsc.status}: ${gsc.note || ''}_`);
  else {
    L.push(`- Window: ${gsc.window} · quick wins: **${gsc.quickWinsCount}** · cannibalization: **${gsc.cannibalizationCount}**`);
    L.push('');
    if (gsc.quickWins.length) {
      L.push('**Fix these first (position 4–20, low CTR):**');
      L.push('');
      L.push('| Query | Position | Impressions | Clicks | CTR |');
      L.push('|---|---|---|---|---|');
      for (const w of gsc.quickWins.slice(0, 15)) L.push(`| ${md(w.query)} | ${w.position} | ${w.impressions} | ${w.clicks} | ${w.ctr}% |`);
      L.push('');
    }
    if (gsc.cannibalization.length) {
      L.push('**Cannibalization (2+ of our URLs on one query):**');
      L.push('');
      for (const c of gsc.cannibalization.slice(0, 10)) {
        L.push(`- **${md(c.query)}** (${c.totalImpressions} impr):`);
        for (const u of c.urls.slice(0, 4)) L.push(`  - pos ${u.position} · ${u.impressions} impr · \`${trunc(safe(u.page), 70)}\``);
      }
      L.push('');
    }
  }
  L.push('');

  // ── 3. Traffic ──
  L.push('## 3. Traffic (Vercel Analytics)');
  if (traffic.status !== 'ok') L.push(`- _${traffic.status}: ${traffic.note || ''}_`);
  else {
    L.push(`- Window: ${traffic.window}`);
    L.push(`- Sessions: **${traffic.sessions}** (${traffic.changeVsPrev.sessions}) · Unique visitors: **${traffic.uniqueVisitors}** (${traffic.changeVsPrev.visitors}) · Pageviews: **${traffic.pageviews}** (${traffic.changeVsPrev.pageviews})`);
    if (traffic.topPages?.length) {
      L.push('');
      L.push('**Top pages:**');
      for (const p of traffic.topPages) L.push(`- \`${trunc(safe(p.path), 60)}\` — ${p.views ?? '?'} views`);
    }
  }
  L.push('');

  // ── 4. Local NAP ──
  L.push('## 4. Local NAP consistency');
  if (nap.status !== 'ok') L.push(`- _${nap.status}: ${nap.note || ''}_`);
  else {
    L.push(`- Canonical: **${nap.canonicalNAP.name}**, ${nap.canonicalNAP.address}, ${nap.canonicalNAP.phone}`);
    L.push(`- Internal build: ${nap.internal.consistent ? '✅ consistent' : '⚠️ inconsistent'} — ${md(nap.internal.note)}`);
    if (!nap.internal.consistent) for (const p of nap.internal.distinctPhones.filter(x => !x.matchesCanonical)) L.push(`  - ${p.value} — ${md(p.note)}`);
    L.push('');
    L.push('| Source | Value shown | Matches canonical? | Note |');
    L.push('|---|---|---|---|');
    for (const r of nap.externalListings) {
      const shows = r.phone || '—';
      const match = r.matchesPhone == null ? '—' : (r.matchesPhone ? '✅' : '❌');
      L.push(`| ${md(r.source)} | ${md(shows)} | ${match} | ${md(r.note)} |`);
    }
  }
  L.push('');

  // ── 5. Content gap ──
  L.push('## 5. Content gap → Blog Queue');
  if (gap.status !== 'ok') L.push(`- _${gap.status}: ${gap.note || ''}_`);
  else {
    L.push(`- Existing posts: ${gap.existingPosts} · gaps found: ${gap.totalGaps} · titles: ${gap.titlesFrom}`);
    L.push(`- Area coverage: ${Object.entries(gap.areaCoverage).map(([a, n]) => `${a} ${n}`).join(' · ')}`);
    L.push('');
    L.push('**Write these (ranked):**');
    L.push('');
    L.push('| # | Suggested title | Area | Theme | Score |');
    L.push('|---|---|---|---|---|');
    gap.topGaps.forEach((g, i) => L.push(`| ${i + 1} | ${md(g.suggestedTitle)} | ${g.area || '—'} | ${md(g.theme)} | ${g.score} |`));
  }
  L.push('');

  // ── Sheet paste row ──
  const sessionsCell = curSessions ?? 'n/a';
  const visitorsCell = traffic.status === 'ok' ? (traffic.uniqueVisitors ?? 'n/a') : 'n/a';
  const formsCell = 'n/a'; // form submissions are not in this read-only suite (wire from Make/Sheets if wanted)
  const topKw = gsc.status === 'ok' ? (gsc.topQuickWinKeyword || 'n/a') : 'n/a';
  const issuesCell = totalTechIssues ?? 'n/a';
  const tsvRow = [date, sessionsCell, visitorsCell, formsCell, topKw, issuesCell].join('\t');

  L.push('## Weekly Analytics Log — paste row');
  L.push('');
  L.push('Copy the line below (tab-separated) into the **Weekly Analytics Log** tab:');
  L.push('');
  L.push('```tsv');
  L.push('date\tsessions\tunique_visitors\tforms\ttop_quick_win_keyword\tissues_found');
  L.push(tsvRow);
  L.push('```');
  L.push('');

  // ── Machine state for next diff ──
  const state = {
    date, sessions: curSessions, uniqueVisitors: traffic.status === 'ok' ? traffic.uniqueVisitors : null,
    softIssues: curSoft, totalTechIssues, quickWins: gsc.status === 'ok' ? gsc.quickWinsCount : null,
    topQuickWin: topKw === 'n/a' ? null : topKw, techMode: tech.status === 'ok' ? tech.mode : null,
  };
  L.push(`${STATE_OPEN}\n${JSON.stringify(state)}\n${STATE_CLOSE}`);
  L.push('');

  return { markdown: L.join('\n'), tsvRow, state };
}

// ─── Write ────────────────────────────────────────────────────────────────────

export function writeReport(results) {
  const date = today();
  const file = repoPath('reports', 'seo', `${date}.md`);
  const prev = previousReport(`${date}.md`);
  const { markdown, tsvRow, state } = renderReport(results, prev);
  mkdirSync(REPORTS_DIR, { recursive: true });
  writeFileSync(file, markdown, 'utf8');
  return { path: `reports/seo/${date}.md`, tsvRow, state, diffedAgainst: prev?.file || null };
}

// Standalone: render from a results file, or gather results then write.
export async function run() {
  const SKILL = 'reporter';
  try {
    const arg = process.argv[2];
    let results;
    if (arg && existsSync(arg)) {
      results = JSON.parse(readFileSync(arg, 'utf8'));
    } else {
      const mods = await Promise.all([
        import('./technical-audit.js'), import('./gsc-quickwins.js'),
        import('./traffic-report.js'), import('./local-nap.js'), import('./content-gap.js'),
      ]);
      results = await Promise.all(mods.map(m => m.run()));
    }
    const out = writeReport(results);
    return ok(SKILL, out);
  } catch (err) {
    return fail(SKILL, `reporter crashed: ${err.message}`);
  }
}

// ─── md helpers ───────────────────────────────────────────────────────────────
function md(s) { return String(s ?? '').replace(/\|/g, '\\|').replace(/\n/g, ' '); }
function safe(s) { return String(s ?? ''); }
function trunc(s, n) { s = String(s ?? ''); return s.length > n ? s.slice(0, n) + '…' : s; }

runStandalone(import.meta.url, run);
